apiVersion: v1
kind: Service
metadata:
  name: cased-shell
spec:
  ports:
  - port: 443
    targetPort: https
    name: https
  # Optional, disabled by default.
  # - port: 80
  #   targetPort: http
  #   name: http
  selector:
    app: cased-shell
