namespace: shell

resources:
# A Cased Shell Deployment, Service, and ServiceAccount
- ../../kustomize/bases/cased-shell
# A SSHD Deployment, Service, and ServiceAccount
- ../../kustomize/bases/kubectl-sshd
# A ClusterRoleBinding granting the the kubectl-sshd ServiceAccount admin access to the cluster.
- clusterrolebindings/kubectl-sshd.yaml

secretGenerator:
- name: cased-shell
  envs:
  - .env

configMapGenerator:
- name: jump
  files:
  - ./jump.yaml
- name: cased-shell
  literals:
  # !!! IMPORTANT !!!
  # Update to match the port of your demo shell.
  - CASED_SHELL_HOSTNAME=localhost:8899
  - CASED_SHELL_TLS=off
  # https://docs.cased.com/docs/environment-variables
- name: kubectl-sshd
  literals:
  # !!! IMPORTANT !!!
  # Set to the authorized_keys entry provided on your Cased Shell settings page, e.g. https://app.cased.com/shell/programs/shell_EXAMPLE/settings. 
  # Quotes do not need to be escaped.
  - PUBLIC_KEY="cert-authority,principals="noreply+org_EXAMPLE@cased.com" ecdsa-sha2-nistp256 AAAAEXAMPLE="
  - KUBECTL_VERSION=v1.20.12
